### PR TITLE
Further non-breaking cleanup & improvements

### PR DESCRIPTION
**Pull request by raphinesse**
See commits for details

### CODE REVIEW

**Comment by brodybits** [comment]
I just pushed a few more changes, would be happy to move them to another PR:
- do not overwrite events object
- use forEach instead of for loop
- use const whenever possible

**Comment by raphinesse** [comment]
Thanks for your extensive review @brodybits!

> I just pushed a few more changes, would be happy to move them to another PR

I'd like to avoid any *additional* changes to prevent conflicts with my *existing work* for apache/cordova-discuss#89. Unfortunately all your suggested additional changes actually do conflict with that.

My plan is as follows

1. Reach a consensus on which parts of apache/cordova-discuss#89 we *do* want
1. Adapt my existing work and get it into master (Including documentation and tests)
1. Do another round of cleanup. Including ES20XXify and all.

So I'd suggest you do not yet create another cleanup PR.

I will squash the test commit you provided, thanks.

#### Regarding the supposed new interface

I've been a bit overzealous here. I will remove the delegation function and add that as part of a PR for apache/cordova-discuss#99. The interface introduced here is *not* as described in apache/cordova-discuss#99 and should be considered private.

I have mixed feelings regarding your proposed changes for the main function. I will elaborate in code comments.

**Comment by raphinesse** [comment]
@brodybits Regarding the suggested changes to the main function:

> do not reassign function arguments - looks ugly and is a bad idea according to: <https://spin.atomicobject.com/2011/04/10/javascript-don-t-reassign-your-function-arguments/>

Even though I don't particularly like to assign to arguments, I like the alternatives here less. Especially because of conflicts with existing work and because I hope for this to be going away with future refactors anyway (see below).

Furthermore, I don't think the dangers outlined in the post above apply to us. We do not use `arguments` at all and never should do so in the future. In ES6+ code we can always use *rest parameters* instead. Moreover, we are not mixing up args as the author does, but refine the exisiting arguments while not changing their meaning.

---

> split up cordovaCreate function to deal with dest dir in a nicer way:

This change breaks the *Single Level of Abstraction* principle ([example](https://medium.com/@yukas/single-level-of-abstraction-1e2bb6a645d7)).

After landing any major breaking changes I *do* want to split the main function up, though. But in a way that actually explains what's happening and improves unit-testability. Something like:
```js
normalizeArguments()
resolveTemplate()
expandTemplate()
```

---

Do you think you can live with my updated changes given my reasoning and plans outlined above?

If this lands I would prepare a preview PR for the work I've done on the breaking changes next.

**Comment by brodybits** [comment]
Thanks @raphinesse for going through my comments. I think the most important thing was not to break any existing tests. While I would like to see the other points addressed sometime I think they are minor enough to leave for later. +1 for cleaning up the internal interface while waiting for agreement on the external interface.

A couple side points:

I wish this PR had come with a reminder of apache/cordova-discuss#89 for the context. (I totally forgot about the discussion, didn't even remember commenting on it until I took another look.) But better late than never:)

I was surprised that you named me as co-author of e020d8d, don't think I had anything to do with the changes there.

**Comment by raphinesse** [comment]
> I wish this PR had come with a reminder of apache/cordova-discuss#89 for the context.

Yes, I thought so too when writing my replies. Sorry for that. My bad :disappointed: 

> I was surprised that you named me as co-author of e020d8d, don't think I had anything to do with the changes there.

I incorporated your changes regarding arguments assignment into the adapter function. Should I remove you?

**Comment by brodybits** [comment]
> I incorporated your changes regarding arguments assignment into the adapter function.

Missed that one (still don't see it). Thanks for the credit, though.

**Pull request merged**
