### PR TITLE
[WIP] Update for nightly dependency builds (cordova-create@2)

### PR DESCRIPTION
**Pull request by brodybits**
This is a proposal to use nightly build of dependencies from npm. Note that this should automatically match the next major release of dependencies when published with the default tag (`latest`).

I think this would give us better consistency. Current situation is that `master` branch of the existing Cordova packages have dependency on patch release of other Cordova packages.

If accepted then I think we should apply this kind of update to `master` branch of all Cordova tools and platform packages.

### CODE REVIEW

**Comment by dpogue** [comment]
We should not point to nightly builds here. The nightly builds automatically have their dependencies updated to reference the other nightlies, so if you want to run nightlies you should install the actual nightly builds. We're also not supposed to tell end users to use nightly builds because those have not been voted to be released.

What this should do is reference the next major that we are targeting.

**Comment by janpio** [comment]
(There is now a discussion going on in the dev mailing list about this @dpogue - you probably want to follow it and post this there.)

**Comment by dpogue** [comment]
(Just saw that, thanks!)

**Comment by brodybits** [comment]
Closing as not wanted according to [[1]](https://lists.apache.org/thread.html/49fc931d20033465f7a2202e5f7009fa04d28bd856ac518338b1d60f@%3Cdev.cordova.apache.org%3E).

As I said in [[1]](https://lists.apache.org/thread.html/49fc931d20033465f7a2202e5f7009fa04d28bd856ac518338b1d60f@%3Cdev.cordova.apache.org%3E) new major version of each Cordova package under development will continue to keep dependency on other patch release versions until we issue the new release. I hope we can solve this someday.

[1] <https://lists.apache.org/thread.html/49fc931d20033465f7a2202e5f7009fa04d28bd856ac518338b1d60f@%3Cdev.cordova.apache.org%3E>

**Pull request closed without merging**
